config/routes.rb
Rails.application.routes.draw do

  root 'user#home'

  #===========LOGIN============
  get 'login' => 'user#login'
  post 'sign_in' => 'user#sign_in'
  post 'logout' => "user#logout"

  #=========VIEW DORMS=========
  get 'view_dorms' => "user#view_dorms"
  get 'admin/modify_slots/:id' => 'admin#modify_slots'
  post 'admin/save' => 'admin#save'

  #===========APPLY============
  post 'apply' => "user#apply"
  get 'new_application' => "user#new_application"
  get 'renew' => "user#renew"
  
  post 'apply/save' => "user#save"
  post 'select' => 'user#select'
  post 'remove' => 'user#remove'
  get 'sort' => 'user#sort'
  
  #==========OTHERS============
  get 'admin/post' => 'admin#post'
  post 'admin/post_it' => 'admin#post_it'
  get 'admin/waitlist' => 'admin#waitlist'
  post 'admin/search' => 'admin#search_by_snum'
  get 'admin/add_to_waitlist' => 'admin#add_to_waitlist'
  get 'admin/grant_dorm' => 'admin#grant_dorm'
  

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/admin/add_to_waitlist.html.erb
<%= @name %>
has been waitlisted
<br>

<%= link_to '<<back', admin_waitlist_path %>

app/views/admin/grant_dorm.html.erb
grant dorm


<%= form_for @resident, :url => root_path do |f| %>
	<% dorm = options_from_collection_for_select(@dorms, 'id', 'dorm_name') %>
	<%= f.select :dorm_id,  dorm %>
<% end %>

app/views/admin/modify_slots.html.erb
<h2><%= @dorm.dorm_name %></h2>

<%= form_tag :class => "form-control", :role => 'form', :action => 'save', :id => @dorm do %>

<div class="allot"><label for='total_slots'>Total slots</label>
<%= number_field :dorm, :total_slots, :class => 'form-control'%></div>
<h4>allotment</h4>

<table class="table allot">
	<tr>
		<th width="20%">Category</th>
		<th width="20%">male</th>
		<th width="20%">female</th>
	</tr>

	<tr>
		<td>Freshmen</td>
		<td><%= number_field :dorm_allotment, :freshie_m, :class => 'form-control'%></td>
		<td><%= number_field :dorm_allotment, :freshie_f, :class => 'form-control' %></td>
	</tr>
	<tr>
		<td>Upperclass</td>
		<td><%= number_field :dorm_allotment, :upperclass_m, :class => 'form-control' %></td>
		<td><%= number_field :dorm_allotment, :upperclass_f, :class => 'form-control' %></td>
	</tr>
	<tr>
		<td>Graduate</td>
		<td><%= number_field :dorm_allotment, :graduate_m, :class => 'form-control' %></td>
		<td><%= number_field :dorm_allotment, :graduate_f, :class => 'form-control' %></td>
	</tr>
</table>

<%= submit_tag 'save', :class => "btn btn-default" %>
<% end %>

<% if @dorm.errors.any? || @dorm_allotment.errors.any?%>
  <div id="error_explanation"> 
    <ul>
    
    <% @dorm.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>

    <% @dorm_allotment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    
    </ul>
  </div>
<% end %>

app/views/admin/post.html.erb
<div class="post">
<h3>Post Announcements</h3>

<%= form_tag :role => 'form', :action => 'post_it' do%>
	<div class="form-group">
		<label>Subject:</label><br>
		<%= text_field(:post, :header, :class => 'form-control') %><br/>
	</div>
	
	<div class="form-group">
		<label>Content:</label><br>
		<%= text_area(:post, :content, :rows => "10%", :class => 'form-control') %><br/>
	</div>

	<%= submit_tag("post", :class => "btn btn-default") %>
<% end %>
</div>

<br>

app/views/admin/save.html.erb
<% if @dorm.errors.any? %>
  <div id="error_explanation"> 
    <ul>
    <% @dorm.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/waitlist.html.erb
<%= form_tag :action => 'search_by_snum', :id => @record do %>

	<%= number_field :record, :student_number %>

<%= submit_tag 'search' %>
<% end %>

<%if @student %>

<table>
	<tr>
		<th>student no.</th>
		<th>name</th>
	</tr>
	
	<tr>
		<td><%=	@student_number %></td>
		<td><%= @student %></td>
		
		<% if @dormer %>
		<td>dormer</td>
		<% elsif !@waitlisted %>		
		
		<td><%=link_to 'add to waitlist', admin_add_to_waitlist_path(:student_number => @student_number, :name => @student)%></td>		

		<%else%>
		<td>already waitlisted</td>	

		<% end %>
	</tr>
</table>
<%end%>


<br>
<h4>waitlist</h4>

	<table>
	<tr>
		<th>student no.</th>
		<th>name</th>
		<th>action</th>
	</tr>
	
	<% @waitlist.each do |x| %>
		<tr>
		<td><%=	x.student_number %></td>
		<td><%= x.first_name + " " + x.last_name %></td>
		
		<td>
			<%= link_to 'grant dorm', admin_grant_dorm_path %> <br>
		</td>
	</tr>
	<%end%>
</table>