config/routes.rb
Rails.application.routes.draw do

  root 'user#home'

  #===========LOGIN============
  get 'login' => 'user#login'
  post 'sign_in' => 'user#sign_in'
  post 'logout' => "user#logout"

  #=========VIEW DORMS=========
  get 'view_dorms' => "user#view_dorms"
  get 'admin/modify_slots/:id' => 'admin#modify_slots'
  post 'admin/save' => 'admin#save'

  #===========APPLY============
  post 'apply' => "user#apply"
  get 'new_application' => "user#new_application"
  get 'renew' => "user#renew"
  
  post 'apply/save' => "user#save"
  post 'select' => 'user#select'
  post 'remove' => 'user#remove'
  get 'sort' => 'user#sort'
  
  #==========OTHERS============
  get 'admin/post' => 'admin#post'
  post 'admin/post_it' => 'admin#post_it'
  get 'admin/waitlist' => 'admin#waitlist'
  post 'admin/search' => 'admin#search_by_snum'
  get 'admin/add_to_waitlist' => 'admin#add_to_waitlist'
  get 'admin/grant_dorm' => 'admin#grant_dorm'
  

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :record

	attr_accessor :password
	before_save :encrypt_password

	validates_presence_of :password, :on => :create
	validates_presence_of :username, :on => :create
	validates_uniqueness_of :username

	def self.authenticate(username, password)
		user = find_by_username(username)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	
	before_filter :logged_in?, :except => [:home, :sign_in]
	
	#uses:
	#user/login.html.erb
	#user/home.html.erb, if logged in
	def home
		if current_user == nil
			@user = User.new
			@announcement = Announcement.all.reverse
			render :login
		end
	end

	#===============Authentication==================
	#ST-1: As a user, I can login
	#ST-2: As a user, I can logout

  	def sign_in
	    username = params[:user][:username]
	    password = params[:user][:password]

	    user = User.authenticate(username, password)

	    if user
	    	session[:user_id] = user.id
		else
			flash[:error] = 'username and password does not match'
		end

		redirect_to :root
  	end

  	def logout
	    if current_user
	      session[:user_id] = nil
	      flash[:notice] = "You have been signed out."
	    end

	    redirect_to :root
  	end	

  	#==================View Dorms====================
  	#ST-4: As a user, I can view the number of slots a dorm can accomodate
  	#ST-5: As a user, I can view the number of slots available in a dorm
  	
  	def view_dorms
		@dorms = Dorm.all

		@oshadmin = Admin.authenticate(current_user.username) == 0? true : false
	end

	#====================Apply=======================
	#ST-6: As a user, I can view of demands in a certain dorm
	#ST-7: As a dorm applicant, I want to choose the dorms I want to apply to
	#ST-8: As a dorm applicant (current dormer), I can renew my slot in the dormitory

	before_filter :apply, :unless => :admin?, :only => [:new_application, :sort]
	before_filter :deny_access, :unless => :renewable?, :only => :renew

	def apply
		app_status = Record.where(student_number:current_user.student_number).first.app_status

		unless app_status == 2 || !renewable?
			redirect_to :renew
		end
	end

	def new_application
		@dormer = renewable?
		@admin = admin?

		if @admin
			@dorms = Dorm.all
		else
			s = Record.generate_tag(current_user)
			d = DormAllotment.select('dorm_id').where(s)
			@dorms = Dorm.where(id: d)
		end
	end

	def renew
		s = Record.where(student_number:current_user.student_number)
		@app_status = s.first.app_status
	end

	def save
		user = Record.where(student_number:current_user.student_number).first
		user.app_status = params[:status]
		user.save

		if(user.app_status == 1)

			a = Applicant.where(student_number:current_user.student_number)
			a.each do |x|
				x.destroy
			end

			dorm = Resident.where(student_number:current_user.student_number).first
			#kailangan bang idagdag yung renewal sa demand?		
			Applicant.create student_number:user.student_number, dorm_id:dorm.dorm_id, is_renewing:true


			redirect_to :back
		else
			redirect_to :new_application
		end
	end

	def select
		@dorm = Dorm.find(params[:id])
		apply = Applicant.create(dorm_id:params[:id], student_number:current_user.student_number, is_renewing:false)
		redirect_to :sort
	end

	def remove
		to_remove = Applicant.where(student_number:current_user.student_number, dorm_id:params[:id]).first
		#dapat may lalabas na are you sure?
		to_remove.destroy
		redirect_to :back
	end

	def sort
		if admin?
			redirect_to :root
		end
		
		a = Applicant.where(student_number:current_user.student_number)
		dorms = Applicant.select('dorm_id').where(student_number:current_user.student_number)
		@dorm = Dorm.where(id:dorms)
	end

	
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_announcements.html.erb
<div>

<h3>Announcements</h3>

<table class="table announcement">
    <% @announcement.each do |x| %>
        <tr><td>
            <h3><%= x.header %></h3>
            <small>posted on:</small>
            <%= x.created_at.to_time.strftime("%b %d, %Y, %I:%M %P") %>
            <br>
            <%= simple_format(x.content) %>
        </td></tr>
    <% end %>
</table>

</div>

app/views/user/home.html.erb
Hi, <%= current_user.username %>!

app/views/user/login.html.erb
<div class="login_container">
    <h2>LOGIN</h2>
    <%= form_for @user, :role => 'form', :as => :user, :url => sign_in_path(@user) do |f| %>
        <div class="form-group">
            <%= f.label 'username:' %><br />
            <%= f.text_field :username %>
        </div>
        <div class="form-group">
            <%= f.label 'password:' %><br />
            <%= f.password_field :password %>
        </div>
    
        <%= f.submit 'login', :class => "btn btn-default" %>&nbsp;&nbsp;&nbsp;            
    
    <% end %>   
</div>

<h3>Announcements</h3>

<table class="table announcement">
    <% @announcement.each do |x| %>
        <tr><td>
            <h3><%= x.header %></h3>
            <small>posted on:</small>
            <%= x.created_at.to_time %>
            <br>
            <%= simple_format(x.content) %>
        </td></tr>
    <% end %>
</table>

app/views/user/new_application.html.erb
 
<% if @dormer%>
	Click
	<%= link_to "here", apply_save_path(:status => 1), method: :post%>
	to renew instead.
	<br>
<% end %>

<br>
<br>  

<div>
<table class="table-striped table table-bordered">
	<tr>
		<th class="center" width="20%">Dorm</th>
		<th class="center" width="20%">Available slots</th>
		<th class="center" width="20%">Demand</th>
		<th class="center" width="20%">Total Slots</th>
		<% unless @admin %> 
			<th class="center" width="20%"></th>
		<% end %>
	</tr>

	<%@dorms.each do |x|%>
	
	<tr>
		<td><%=	x.dorm_name %></td>
		<td class="center"><%= Dorm.available(x.id) %></td>			
		<td class="center"><%= Applicant.demand(x.id)  %></td>			
		<td class="center"><%=	x.total_slots %></td>	
		
		<% unless @admin %> 
			<td class="center">
				<% if Applicant.applied(current_user.student_number, x.id) == nil%>
					<%= link_to 'select', select_path(:id => x.id), method: :post %>
				<% else %>
				Desired already
				<%end%>
			</td>		
		<% end %>
				
	</tr>

	<%end%>
</table>
</div>

<% if !@admin %> 
<br>
<%= link_to 'arrange dorm preferrence>>', sort_path %>
<% end %>
<br>
<br>

app/views/user/renew.html.erb
<% if @app_status == 0 %>
	<%= link_to "renew", apply_save_path(:status => 1), method: :post%>
	<br>
	<%= link_to "apply for other dorms", apply_save_path(:status => 2), method: :post %>
	dapat may mag-pop up na parang if you click this, you're going to be considered as a new applicant
	<br>
<% elsif @app_status == 1 %>
	You have submitted your application for renewal, please wait for further notice
<% end %> 

app/views/user/sort.html.erb
<div>
<table class="table-striped table table-bordered">
	<tr>
		<th class="center" width="20%">Dorm</th>
		<th class="center" width="20%">Available slots</th>
		<th class="center" width="20%">Demand</th>
		<th class="center" width="20%">Total Slots</th>
		<th class="center" width="20%"></th>
	</tr>

	<%@dorm.each do |x|%>
	
	<tr>
		<td><%=	x.dorm_name %></td>
		<td class="center"><%= Dorm.available(x.id) %></td>			
		<td class="center"><%= Applicant.demand(x.id)  %></td>			
		<td class="center"><%=	x.total_slots %></td>	
		<td class="center"><%= link_to 'remove', remove_path(:id => x.id), method: :post %></td>		
	</tr>

	<%end%>
</table>
</div>


<br>
<%= link_to '<<back to dorm selection', new_application_path %>
<br>
<br>

app/views/user/view_dorms.html.erb
<div>
<table class="table-striped table table-bordered">
	<tr>
		<th class="center" width="40%">Dorm</th>
		<th class="center" width="20%">Available slots</th>
		<th class="center" width="20%">Total slots</th>
		<% if @oshadmin %>
			<th class="center" width="20%"></th>
		<% end %>
	</tr>

	<%@dorms.each do |x|%>
	
	<tr>
		<td><%=	x.dorm_name %></td>
		<td class="center"><%= Dorm.available(x.id) %></td>			
		<td class="center"><%=	x.total_slots %></td>	
		
		<% if @oshadmin%>
			<td class="center"><%= link_to "modify", "admin/modify_slots/" + x.id.to_s %></td>
		<% end %>
				
	</tr>

	<%end%>
</table>
</div>