config/routes.rb
Rails.application.routes.draw do

  root 'user#home'

  #===========LOGIN============
  get 'login' => 'user#login'
  post 'sign_in' => 'user#sign_in'
  post 'logout' => "user#logout"

  #=========VIEW DORMS=========
  get 'view_dorms' => "user#view_dorms"
  get 'admin/modify_slots/:id' => 'admin#modify_slots'
  post 'admin/save' => 'admin#save'

  #===========APPLY============
  post 'apply' => "user#apply"
  get 'new_application' => "user#new_application"
  get 'renew' => "user#renew"
  
  post 'apply/save' => "user#save"
  post 'select' => 'user#select'
  post 'remove' => 'user#remove'
  get 'sort' => 'user#sort'
  
  #==========OTHERS============
  get 'admin/post' => 'admin#post'
  post 'admin/post_it' => 'admin#post_it'
  get 'admin/waitlist' => 'admin#waitlist'
  post 'admin/search' => 'admin#search_by_snum'
  get 'admin/add_to_waitlist' => 'admin#add_to_waitlist'
  get 'admin/grant_dorm' => 'admin#grant_dorm'
  

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Office of Student Housing <br>
    University of the Philippines <br>
    Diliman, Quezon City
  </small>
</footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Office of Student Housing", root_path, id: "logo" %>
    <nav>
      <% if current_user %>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Apply", new_application_path %></li>
        <li><%= link_to "Dorms", view_dorms_path %></li>
        <% if Admin.authenticate(current_user.username) != nil %>
          <li><%= link_to "Post", admin_post_path %></li>
          <li><%= link_to "Waitlist", admin_waitlist_path %></li>
        <% end %>
        <li><%= link_to "Logout", logout_path, method: :post%></li>
      </ul>
      <% end %>
    </nav>

  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title> Dormitoryo </title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>

	<% flash.each do |name, msg| %>
		<%= content_tag :div, msg, :id => "flash_#{name}" %>
	<% end %>

	<div class="container">
   <%= yield %>
  </div>

  <%= render 'layouts/footer' %>
</body>
</html>